#ifndef EMUONEUTIL_GLOBAL_H
#define EMUONEUTIL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EMUONEUTIL_LIBRARY)
#  define EMUONEUTIL_EXPORT Q_DECL_EXPORT
#else
#  define EMUONEUTIL_EXPORT Q_DECL_IMPORT
#endif

#endif // EMUONEUTIL_GLOBAL_H
