#ifndef EMUONE_UTIL_GLOBAL_HPP
#define EMUONE_UTIL_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(EMUONE_UTIL_LIBRARY)
#define EMUONE_UTIL_EXPORT Q_DECL_EXPORT
#else
#define EMUONE_UTIL_EXPORT Q_DECL_IMPORT
#endif

#endif // EMUONE_UTIL_GLOBAL_HPP
